### ISSUE TITLE
Wallet leaves behind dust

### ISSUE THREAD

**Issue by Deozaan** [tezbox/tezbox-web-wallet#10]
The web wallet only shows two decimal places, but accounts can have up to four. This means if you try to empty a wallet and transfer all funds to another account, you will probably leave behind some "dust."

Then, sometimes that dust gets "locked" in the wallet due to #9

**Comment by stephenandrews** [comment]
Added Max button to send the max amount. The tezos protocol requires at least 0.000001tez to be left in a tz account
